spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info_clients?useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
#      Use none for production and migration tool like liquibase
      ddl-auto: update